FROM golang:1.25-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 go build -o /secrets-init ./cmd/secrets

FROM scratch

COPY --from=builder /secrets-init /secrets-init

ENTRYPOINT ["/secrets-init"]
