FROM golang:1.27-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 go build -o /worker ./cmd/worker

FROM alpine:3.24
RUN apk add --no-cache ca-certificates tzdata
COPY --from=builder /worker /worker

WORKDIR /
CMD ["/worker"]
